[package]
name = "macmon"
version = "0.6.0"
edition = "2024"

[lints.rust]
non_camel_case_types = "allow"
unreachable_code = "allow"
unused_assignments = "allow"
unused_imports = "deny"

[lints.clippy]
needless_range_loop = "allow"
single_match = "allow"

[profile.release]
panic = "abort"
strip = false
lto = false

[dependencies]
chrono = "0.4.39"
clap = { version = "4.5.31", features = ["derive"] }
core-foundation = "0.10.0"
libc = "0.2.170"
num-traits = "0.2.19"
ratatui = { version = "0.29.0", features = ["serde"] }
serde = { version = "1.0.218", features = ["derive"] }
serde-inline-default = "0.2.3"
serde_json = "1.0.139"
