[package]
name = "macmon"
version = "0.4.2"
edition = "2021"

[lints.rust]
non_camel_case_types = "allow"
unused_assignments = "allow"
unreachable_code = "allow"

[profile.release]
panic = "abort"
strip = false

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
core-foundation = "0.10.0"
libc = "0.2.168"
num-traits = "0.2.19"
ratatui = { version = "0.29.0", features = ["serde"] }
serde = { version = "1.0.216", features = ["derive"] }
serde-inline-default = "0.2.3"
serde_json = "1.0.133"
